# Generated by Django 5.0.3 on 2024-04-06 12:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
